name: Sync from upstream
on:
  schedule:
    - cron: "17 * * * *"  # hourly at :17; adjust as desired
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allows pushing to the fork
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # we’ll push with GITHUB_TOKEN
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/theonlytomtom/paperstreetco.git
          git fetch upstream

      - name: Fast-forward main from upstream/main
        run: |
          git checkout main
          # Attempt a clean fast-forward. If there are local-only commits, prefer a merge; see alt step below.
          git merge --ff-only upstream/main || (
            echo "Fast-forward failed; trying a merge..." &&
            git merge --no-edit upstream/main
          )

      - name: Push updated main to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} main

